### ISSUE TITLE
Rename this repo to piecioshka

### ISSUE THREAD

**Issue by JB1905** [piecioshka/piecioshka#1]
Hi!
If you want to display README file from this project on your profile page, change the name to `piecioshka`.

**Comment by piecioshka** [comment]
Oh, great! Thanks! 🍺 

@JB1905 How did you know that to do it?

**Comment by JB1905** [comment]
I follow front-end stars on GitHub 😃:
- https://github.com/sdras/sdras
- https://github.com/cassidoo/cassidoo
- https://github.com/tannerlinsley/tannerlinsley

and more...

**Comment by JB1905** [comment]
And, of course 🤗:
- https://github.com/piecioshka/piecioshka
